### ISSUE TITLE
Why can't I configure the output of logs to a file in the aiogram bot?

### ISSUE THREAD

**Issue by Sandorro** [vd2org/betterlogging#10]
I'm writing a aiogram bot and I want the logs to be written to a text file. Logs are written to the console, but if I specify a file for output, an error appears. How can I solve this problem?

Code:
```
...
if __name__ == '__main__':
    if debug == 1:
         betterlogging.basic_colorized_config(level=betterlogging.DEBUG, filename='logging_history.txt')
    if info == 1:
         betterlogging.basic_colorized_config(level=betterlogging.INFO, filename='logging_history.txt')
    betterlogging.basic_colorized_config(level=betterlogging.WARNING, filename='logging_history.txt')
    betterlogging.basic_colorized_config(level=betterlogging.ERROR, filename='logging_history.txt')
    betterlogging.basic_colorized_config(level=betterlogging.CRITICAL, filename='logging_history.txt')
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\Alexander\Documents\testProject\parser\new\parser\chat.py", line 500, in <module>
    betterlogging.basic_colorized_config(level=betterlogging.INFO, filename='logging_history.txt')
  File "C:\Users\Alexander\Documents\testProject\venv\lib\site-packages\betterlogging\__init__.py", line 50, in basic_colorized_config
    return logging.basicConfig(**kwargs)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2030, in basicConfig
    raise ValueError("'stream' or 'filename' should not be "
ValueError: 'stream' or 'filename' should not be specified together with 'handlers'
```

**Comment by vd2org** [comment]
Hi, Sandorro! 

The library not meant to be used as file logger. 
Colored output is useful for real-time monitoring, not for long-term archiving. 
To save logs to a file, use the standard handler for the same logger.
